services:
  advent-calendar:
    container_name: advent-calendar
    build:
      context: .
      args:
        - VITE_APP_BASE_PATH=$VITE_APP_BASE_PATH
    restart: always
    networks:
      - jenkins
networks:
  jenkins:
    external: true
